ALTER TABLE IF EXISTS payments DROP COLUMN IF EXISTS quote_id;
ALTER TABLE IF EXISTS payments ALTER COLUMN provider_amount DROP NOT NULL;
ALTER TABLE IF EXISTS payments ALTER COLUMN total_amount DROP NOT NULL;